// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: main.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PasteService_GetPasteById_FullMethodName = "/proto.PasteService/GetPasteById"
	PasteService_CreatePaste_FullMethodName  = "/proto.PasteService/CreatePaste"
)

// PasteServiceClient is the client API for PasteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PasteServiceClient interface {
	GetPasteById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Paste, error)
	CreatePaste(ctx context.Context, in *PasteRequest, opts ...grpc.CallOption) (*Paste, error)
}

type pasteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPasteServiceClient(cc grpc.ClientConnInterface) PasteServiceClient {
	return &pasteServiceClient{cc}
}

func (c *pasteServiceClient) GetPasteById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Paste, error) {
	out := new(Paste)
	err := c.cc.Invoke(ctx, PasteService_GetPasteById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pasteServiceClient) CreatePaste(ctx context.Context, in *PasteRequest, opts ...grpc.CallOption) (*Paste, error) {
	out := new(Paste)
	err := c.cc.Invoke(ctx, PasteService_CreatePaste_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasteServiceServer is the server API for PasteService service.
// All implementations must embed UnimplementedPasteServiceServer
// for forward compatibility
type PasteServiceServer interface {
	GetPasteById(context.Context, *Id) (*Paste, error)
	CreatePaste(context.Context, *PasteRequest) (*Paste, error)
	mustEmbedUnimplementedPasteServiceServer()
}

// UnimplementedPasteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPasteServiceServer struct {
}

func (UnimplementedPasteServiceServer) GetPasteById(context.Context, *Id) (*Paste, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPasteById not implemented")
}
func (UnimplementedPasteServiceServer) CreatePaste(context.Context, *PasteRequest) (*Paste, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePaste not implemented")
}
func (UnimplementedPasteServiceServer) mustEmbedUnimplementedPasteServiceServer() {}

// UnsafePasteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PasteServiceServer will
// result in compilation errors.
type UnsafePasteServiceServer interface {
	mustEmbedUnimplementedPasteServiceServer()
}

func RegisterPasteServiceServer(s grpc.ServiceRegistrar, srv PasteServiceServer) {
	s.RegisterService(&PasteService_ServiceDesc, srv)
}

func _PasteService_GetPasteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasteServiceServer).GetPasteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasteService_GetPasteById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasteServiceServer).GetPasteById(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasteService_CreatePaste_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasteServiceServer).CreatePaste(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasteService_CreatePaste_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasteServiceServer).CreatePaste(ctx, req.(*PasteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PasteService_ServiceDesc is the grpc.ServiceDesc for PasteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PasteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PasteService",
	HandlerType: (*PasteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPasteById",
			Handler:    _PasteService_GetPasteById_Handler,
		},
		{
			MethodName: "CreatePaste",
			Handler:    _PasteService_CreatePaste_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
